build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  # amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Hass Maestro"
  org.opencontainers.image.description: "Home Assistant lights orchestrator"
  org.opencontainers.image.source: "https://github.com/lucasfeijo/hass-maestro"
  org.opencontainers.image.licenses: "Apache License 2.0"
