name: Hass Maestro
version: "1.0.2"
slug: maestro
description: Home Assistant lights orchestrator
url: https://github.com/lucasfeijo/hass-maestro
arch:
  - aarch64
  - amd64
startup: services
homeassistant_api: true
ports:
  8080/tcp: 8080
image: "ghcr.io/lucasfeijo/{arch}-addon-maestro"
