name: Hass Maestro
version: "0.1.0"
slug: maestro
description: Swift server providing /run endpoint
url: https://github.com/user/hass-maestro
arch:
  - aarch64
  - amd64
startup: services
boot: auto
host_network: false
options: {}
schema: {}
ports:
  8080/tcp: 8080
image: "ghcr.io/user/{arch}-addon-maestro"
