# Example automation to keep WLED segment 0 (Main) at full brightness
# when any TV shelf segment turns on
alias: Ensure WLED main brightness
mode: queued
trigger:
  - platform: state
    entity_id:
      - light.wled_tv_shelf_1
      - light.wled_tv_shelf_2
      - light.wled_tv_shelf_3
      - light.wled_tv_shelf_4
      - light.wled_tv_shelf_5
    to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.wled_tv_shelf_main
      brightness_pct: 100
