name: Build Swift SDK Base Image

on:
  push:
    branches: [ main ]
    paths: [ 'maestro/Dockerfile.base' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: swift-sdk-base
  SWIFT_VERSION: "6.1.2"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if image already exists
      id: check-image
      run: |
        # Check if the specific version tag already exists
        if docker manifest inspect ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.SWIFT_VERSION }} >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Log in to the Container registry
      if: steps.check-image.outputs.exists != 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      if: steps.check-image.outputs.exists != 'true'
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ env.SWIFT_VERSION }}
          type=raw,value=latest

    - name: Build and push Docker image
      if: steps.check-image.outputs.exists != 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./maestro
        file: ./maestro/Dockerfile.base
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Skip build - image already exists
      if: steps.check-image.outputs.exists == 'true'
      run: |
        echo "Image ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.SWIFT_VERSION }} already exists, skipping build" 